"""Generate YARA and Sigma detection rules from observed static + dynamic behavior."""
from __future__ import annotations

import datetime as _dt
import re
from collections.abc import Iterable

from .types import Detection, IOCRecord

_INTERESTING_KEYWORDS = (
    "http", "cmd", "powershell", "reg", "schtasks", "vssadmin", "mutex",
    "inject", "debug", "vmware", "vbox", "encrypt", "ransom", "bitcoin",
    ".dll", ".exe", "\\run", "/bin/", "wget", "curl", "socket",
)
_STR_ESCAPE = re.compile(r'([\\"])')


def _safe_id(value: str) -> str:
    out = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if out and out[0].isdigit():
        out = "r_" + out
    return out or "rule"


def _yara_escape(s: str) -> str:
    return _STR_ESCAPE.sub(r"\\\1", s)


def _pick_strings(strings: Iterable[str], limit: int = 20) -> list[str]:
    seen: set[str] = set()
    scored: list[tuple[int, str]] = []
    for s in strings:
        s = s.strip()
        if not (6 <= len(s) <= 80):
            continue
        if s in seen:
            continue
        seen.add(s)
        low = s.lower()
        score = sum(2 for kw in _INTERESTING_KEYWORDS if kw in low)
        score += min(len(s) // 16, 3)
        if score > 0:
            scored.append((score, s))
    scored.sort(key=lambda t: (-t[0], t[1]))
    return [s for _, s in scored[:limit]]


def generate_yara(
    sample, static_info: dict, iocs: list[IOCRecord], detections: list[Detection]
) -> tuple[str, str]:
    rule_name = f"APEIRON_{_safe_id(sample.sha256[:12] or sample.id[:12])}"
    fmt = static_info.get("file_format", "unknown")
    picked = _pick_strings(static_info.get("strings", []))

    string_lines = []
    for i, s in enumerate(picked):
        string_lines.append(f'        $s{i} = "{_yara_escape(s)}"')
    # Add network IOCs as strings too.
    net = [i.value for i in iocs if i.ioc_type in ("domain", "url", "ip")][:10]
    for j, val in enumerate(net):
        string_lines.append(f'        $n{j} = "{_yara_escape(val)}"')

    if fmt == "PE":
        magic_cond = "uint16(0) == 0x5A4D"
    elif fmt == "ELF":
        magic_cond = "uint32(0) == 0x464C457F"
    else:
        magic_cond = "true"

    str_count = len(picked) + len(net)
    if str_count:
        any_n = min(3, str_count)
        condition = f"{magic_cond} and {any_n} of them"
        strings_block = "\n".join(string_lines)
    else:
        condition = magic_cond
        strings_block = "        $a = { 00 }"

    tags = " ".join(sample.tags) if sample.tags else "auto-generated"
    techniques = sorted({m for d in detections for m in d.mitre})
    ts = _dt.datetime.utcnow().strftime("%Y-%m-%d")

    content = f"""/*
 * Auto-generated by APEIRON from observed behavior.
 * Sample: {sample.filename}
 * SHA256: {sample.sha256}
 */
rule {rule_name}
{{
    meta:
        author = "APEIRON"
        description = "Behavioral signature for {sample.filename}"
        date = "{ts}"
        sha256 = "{sample.sha256}"
        verdict = "{sample.verdict}"
        threat_score = "{sample.threat_score}"
        tags = "{tags}"
        mitre_attack = "{', '.join(techniques)}"
    strings:
{strings_block}
    condition:
        {condition}
}}
"""
    return rule_name, content


def generate_sigma(
    sample, iocs: list[IOCRecord], detections: list[Detection]
) -> tuple[str, str]:
    rule_id = sample.id[:8]
    domains = [i.value for i in iocs if i.ioc_type == "domain"][:25]
    ips = [i.value for i in iocs if i.ioc_type == "ip"][:25]
    regs = [i.value for i in iocs if i.ioc_type == "registry_key"][:25]
    mutexes = [i.value for i in iocs if i.ioc_type == "mutex"][:25]
    techniques = sorted({m for d in detections for m in d.mitre})
    det_names = ", ".join(d.name for d in detections) or "static indicators"
    ts = _dt.datetime.utcnow().strftime("%Y/%m/%d")
    level = (
        "critical" if sample.threat_score >= 70
        else "high" if sample.threat_score >= 35
        else "medium"
    )

    def _yaml_list(items: list[str]) -> str:
        return "\n".join(f"            - '{i}'" for i in items)

    detection_sections: list[str] = []
    selection_refs: list[str] = []

    if domains or ips:
        net_items = domains + ips
        detection_sections.append(
            "    selection_network:\n"
            "        DestinationHostname|contains:\n"
            f"{_yaml_list(net_items)}"
        )
        selection_refs.append("selection_network")
    if regs:
        detection_sections.append(
            "    selection_registry:\n"
            "        TargetObject|contains:\n"
            f"{_yaml_list(regs)}"
        )
        selection_refs.append("selection_registry")
    if mutexes:
        detection_sections.append(
            "    selection_mutex:\n"
            "        Mutex|contains:\n"
            f"{_yaml_list(mutexes)}"
        )
        selection_refs.append("selection_mutex")

    if not detection_sections:
        detection_sections.append(
            "    selection_hash:\n"
            "        Hashes|contains:\n"
            f"            - 'SHA256={sample.sha256}'"
        )
        selection_refs.append("selection_hash")

    condition = " or ".join(selection_refs)
    tags = "\n".join(f"    - attack.{t.lower()}" for t in techniques) or "    - attack.execution"

    content = f"""title: APEIRON behavioral detection {sample.filename}
id: apeiron-{rule_id}
status: experimental
description: >
    Auto-generated Sigma rule from APEIRON sandbox observations
    (detections: {det_names}).
author: APEIRON
date: {ts}
references:
    - APEIRON sandbox report for {sample.sha256}
logsource:
    category: process_creation
    product: windows
detection:
{chr(10).join(detection_sections)}
    condition: {condition}
falsepositives:
    - Unknown
level: {level}
tags:
{tags}
"""
    return f"apeiron-{rule_id}", content
